# -*- coding: utf-8 -*-
"""func10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSRGuGgE5Ez3u_F23vGPb78UVslnZ9Ga
"""

def add(a,b):
  return a+b

def square(num):
  return num**2

def display(result):
  print(result)

display(square(add(10,15)))

def greet(name):
  return name
display(greet("welcome to class"))
display(greet("welcome to class"))
display(greet("welcome to class"))

def name(name):
  print("hello",name)
name("hello")
name("uday")
name("rohit")

def square(num):
  return num**2
display(square(22))
display(square(32))
display(square(2))

def calculate_area(lenght,breadth):
  return lenght*breadth
display(calculate_area(15,8))

def add(a,b):
  return a+b
def subtract(a,b):
  return a-b
display(add(10,10))
display(subtract(10,5))

def cube(num):
  return num**3
def double(num):
  return num*2
display(cube(4))
display(double(5))

def square(num):
  return num**2
def double(num):
  return num*2
display(square(double(5)))

def add(a,b):
  return a+b
def multiply(a,b):
  return a*b
display(multiply(add(5,3),2))

def add(a,b):
  return a+b
def subtract(a,b):
  return a-b
def multiply(a,b):
  return a*b
def divde(a,b):
  return a/b
display(add(40,10))
display(subtract(40,10))
display(multiply(40,10))
display(divde(40,10))

def add(a,b):
  return a+b
def square(num):
  return num**2
display(square(add(10,15)))

def func(num):
  print(num)
  if num>0:
    func(num-1)
func(10)

def func(num):
  print(num)
  if num<10:

   func(num+1)
func(0)

def func(num):
  print(num)
  if num<=100:
    func(num+2)
func(0)

def sum(num):
    if num == 0:
        return 0
    return num + sum(num-1)

display(sum(10))

def factorial(n):
  #base case
  if n==0 or n==1:
    return 1
  #recursive case
  else:
    return n* factorial(n-1)
print(factorial(5))

def add(num):
  pass

num =add(10)
print(num)

